export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';

export const GET_WORKERS_REQUEST = 'GET_WORKERS_REQUEST';
export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';